# A library of snmp commands to be used in testing.
standard_snmp_command_pairs = [
    # ("snmp<get/walk/table>", "<resource>", "<Description>"),
    ("snmpwalk", "RSU-MIB::rsuSRMStatusTable", "Can a messages be stored for transmission?"),
    ("snmpwalk", "RSU-MIB::rsuDsrcForwardTable", "Can messages be forwarded?"),
    ("snmpwalk", "RSU-MIB::rsuSysDescription", "Can the make and manufacturer codes be read?"),
    ("snmpget", "RSU-MIB::rsuId.0", "Can the serial number be read?"),
    ("snmpget", "RSU-MIB::rsuGpsOutputString.0", "Can the GPS coordinates be read?"),
    ("snmpget", "RSU-MIB::rsuMode.0", "Can the current operational status be read?"),
    ("snmpget", "RSU-MIB::rsuFirmwareVersion.0", "Can the firmware version be read?"),
    ("snmpwalk", "UCD-SNMP-MIB::systemStats", "Can the CPU statistics be read?"),
    ("snmpwalk", "UCD-SNMP-MIB::memory", "Can memory statistics be read?"),
]

# Space for a set of custom snmp commands to be used in testing. These can be generated by the user.
custom_snmp_command_pairs = [
    # ("snmp<get/walk/table>", "<resource>", "<Description>"),
]
